import { Gladiator } from "./models";


export const enemyGladiators: Gladiator[] = [
    {
        id: '100',
        name: "Reptilisk Hatchling",
        stamina: 0,
        estimatedPower: 7,
        knownTraits: ["Savage"],
        truePower: 8,
        hiddenTraits: [],
        description: "A reptilisk hatchling of the reptilisk class, known for being savage.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '101',
        name: "Reptilisk Stalker",
        stamina: 0,
        estimatedPower: 12,
        knownTraits: ["Savage", "Fast"],
        truePower: 13,
        hiddenTraits: [],
        description: "A reptilisk stalker of the reptilisk class, known for being savage, fast.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '102',
        name: "Reptilisk Alpha",
        stamina: 0,
        estimatedPower: 27,
        knownTraits: ["Savage", "Bloodthirsty"],
        truePower: 29,
        hiddenTraits: [],
        description: "A reptilisk alpha of the reptilisk class, known for being savage, bloodthirsty.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '103',
        name: "Orcling",
        stamina: 0,
        estimatedPower: 9,
        knownTraits: ["Stalwart"],
        truePower: 7,
        hiddenTraits: [],
        description: "An orcling of the orc class, known for being stalwart.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '104',
        name: "Orc Brute",
        stamina: 0,
        estimatedPower: 16,
        knownTraits: ["Stalwart", "Lucky"],
        truePower: 14,
        hiddenTraits: [],
        description: "An orc brute of the orc class, known for being stalwart, lucky.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '105',
        name: "Orc Warboss",
        stamina: 0,
        estimatedPower: 30,
        knownTraits: ["Stalwart", "Adamant"],
        truePower: 32,
        hiddenTraits: [],
        description: "An orc warboss of the orc class, known for being stalwart, adamant.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '106',
        name: "Tribal Whelp",
        stamina: 0,
        estimatedPower: 8,
        knownTraits: ["Bloodthirsty"],
        truePower: 9,
        hiddenTraits: [],
        description: "A tribal whelp of the barbarian class, known for being bloodthirsty.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '107',
        name: "Arena Berserker",
        stamina: 0,
        estimatedPower: 18,
        knownTraits: ["Bloodthirsty", "Savage"],
        truePower: 20,
        hiddenTraits: [],
        description: "An arena berserker of the barbarian class, known for being bloodthirsty, savage.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '108',
        name: "Warlord of Ash",
        stamina: 0,
        estimatedPower: 35,
        knownTraits: ["Bloodthirsty", "Cunning"],
        truePower: 36,
        hiddenTraits: [],
        description: "A warlord of ash of the barbarian class, known for being bloodthirsty, cunning.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '109',
        name: "Mistling",
        stamina: 0,
        estimatedPower: 7,
        knownTraits: ["Ghost"],
        truePower: 9,
        hiddenTraits: [],
        description: "A mistling of the specter class, known for being ghost.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '110',
        name: "Specter Adept",
        stamina: 0,
        estimatedPower: 17,
        knownTraits: ["Ghost", "Cunning"],
        truePower: 16,
        hiddenTraits: [],
        description: "A specter adept of the specter class, known for being ghost, cunning.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '111',
        name: "Void Wraith",
        stamina: 0,
        estimatedPower: 33,
        knownTraits: ["Ghost", "Fast"],
        truePower: 31,
        hiddenTraits: [],
        description: "A void wraith of the specter class, known for being ghost, fast.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '112',
        name: "Scrap Drone",
        stamina: 0,
        estimatedPower: 6,
        knownTraits: ["Tireless"],
        truePower: 7,
        hiddenTraits: [],
        description: "A scrap drone of the combat bot class, known for being tireless.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '113',
        name: "War Construct",
        stamina: 0,
        estimatedPower: 14,
        knownTraits: ["Tireless", "Mechslayer"],
        truePower: 13,
        hiddenTraits: [],
        description: "A war construct of the combat bot class, known for being tireless, mechslayer.",
        status: "RESTING",
        lastRefresh: 0
      },
      {
        id: '114',
        name: "Omega-Class Automaton",
        stamina: 0,
        estimatedPower: 27,
        knownTraits: ["Tireless", "Adamant"],
        truePower: 29,
        hiddenTraits: [],
        description: "An omega-class automaton of the combat bot class, known for being tireless, adamant.",
        status: "RESTING",
        lastRefresh: 0
      },
];